-- Agent 热门视频风格模板初始化
-- 执行库：bang_yi
-- 用途：补充抖音/即梦风格的热门视频模板，供 AI 视频页和 Agent 自动选模板使用

INSERT INTO video_template
    (name, code, category, description, prompt_template, style_preset, duration_range, max_images, max_text_length, status, sort)
VALUES
    ('朝代换装汉服', 'dynasty_hanfu_switch', 'costume_change',
     '现代到唐宋明的朝代换装汉服大片，适合国风爆款短视频',
     '同一位{gender}性主角 {username}，{age}岁，来自{city}，从现代日常穿搭一路切换成唐制、宋制、明制汉服。人物始终为同一人，保留五官一致性，衣袂和披帛随风摆动，长廊或庭院场景，像国风电影换装大片，核心表达：{message}。',
     'elegant', '12-20', 4, 280, 1, 101),
    ('花下汉服定妆', 'hanfu_blossom_closeup', 'costume_change',
     '桃花庭院里的汉服定妆特写，适合温柔出片',
     '同一位{gender}性主角 {username}，在{city}的古风庭院或桃花树下，以汉服定妆照和轻动作镜头呈现。服饰精致、发饰清雅、神态温柔，电影级近景和半身特写结合，氛围治愈克制，核心表达：{message}。',
     'elegant', '10-16', 4, 240, 1, 102),
    ('动漫真人 Coser', 'anime_coser_real', 'cosplay',
     '热门二次元角色真人化 cos 质感，适合角色风视频',
     '将 {username} 打造成真人化动漫 Coser，保留本人五官一致性，发型、服装和配件有二次元改编感。棚拍或舞台环境，色彩鲜明，角色感强但仍然真实，像高质感真人漫改短片，核心表达：{message}。',
     'energetic', '10-18', 4, 260, 1, 111),
    ('漫改女主舞台感', 'comic_heroine_stage', 'cosplay',
     '高能漫改女主出场，适合英雄感和少女感',
     '同一位主角 {username} 作为漫改女主出场，镜头带有舞台感和海报感，造型凌厉或甜酷，发丝和服装有动态张力，场景干净、配色明确，像一支高完成度角色出场 PV，核心表达：{message}。',
     'energetic', '10-16', 4, 260, 1, 112),
    ('室内胶片妆造', 'indoor_film_makeup', 'cinematic_portrait',
     '影视人物妆造的室内胶片人像，适合高级氛围感',
     '以 {username} 为主角，打造室内胶片妆造人像。化妆镜、窗边、复古房间或酒店空间，35mm 胶片颗粒，暖光与阴影层次分明，真实皮肤、成熟妆容、电影试镜花絮感，核心表达：{message}。',
     'elegant', '10-18', 4, 260, 1, 121),
    ('复古电影海报脸', 'retro_movie_poster', 'cinematic_portrait',
     '复古港风与电影海报质感，适合妆造大片',
     '同一位主角 {username} 呈现复古电影海报气质，强情绪眼神，复古室内或影棚空间，浓郁但高级的光影，对比色和胶片质感结合，像老港片定妆海报，核心表达：{message}。',
     'romantic', '10-16', 4, 240, 1, 122),
    ('蛇妖觉醒', 'snake_spirit_awakening', 'fantasy_transform',
     '东方蛇妖变身题材，适合奇幻妖系大片',
     '让 {username} 化身为东方蛇妖觉醒版本，保留本人五官识别度，墨绿与暗金色系，异瞳、蛇系眼妆和高级妖异氛围，宫殿、月夜或烛火场景，神秘、不低俗、不恐怖，核心表达：{message}。',
     'romantic', '12-20', 4, 280, 1, 131),
    ('白骨精月夜前传', 'bone_spirit_moonlight', 'fantasy_transform',
     '白骨精灵感改编的人物前传，适合月夜妖姬氛围',
     '让 {username} 化身为白骨精前传灵感角色，苍白骨相美人、银白配饰、冷月和薄雾环境，东方妖异美学，画面高级克制，禁止血腥猎奇，像神秘人物电影预告，核心表达：{message}。',
     'elegant', '12-20', 4, 280, 1, 132),
    ('从童年到美少女', 'childhood_to_beauty', 'growth_story',
     '从童年一路成长到成年高光时刻的时间线故事',
     '以 {username} 为主角，做一支从童年、校园到成年阶段的成长时间线短片。场景按人生阶段切换，人物始终为同一人，情绪温暖、真实、有回忆感，不做未成年性感化，像人生纪录片混剪，核心表达：{message}。',
     'natural', '14-22', 5, 300, 1, 141),
    ('像素青春时间线', 'pixel_youth_timeline', 'growth_story',
     '像素青春与怀旧成长结合，适合回到过去题材',
     '以 {username} 为主角，做一支像素青春时间线视频。16-bit 怀旧画面与现实人物成长片段结合，电话亭、操场、旧街道等元素串联，从过去一路走到现在，情绪青春、怀旧、治愈，核心表达：{message}。',
     'natural', '12-18', 5, 280, 1, 142)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    category = VALUES(category),
    description = VALUES(description),
    prompt_template = VALUES(prompt_template),
    style_preset = VALUES(style_preset),
    duration_range = VALUES(duration_range),
    max_images = VALUES(max_images),
    max_text_length = VALUES(max_text_length),
    status = VALUES(status),
    sort = VALUES(sort),
    update_time = NOW();
