CREATE TABLE IF NOT EXISTS `agent_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` int NOT NULL DEFAULT 0 COMMENT '用户ID',
  `capability_code` varchar(64) NOT NULL DEFAULT '' COMMENT '能力编码',
  `enabled` tinyint NOT NULL DEFAULT 0 COMMENT '是否启用:0否 1是',
  `authorize_mode` varchar(32) NOT NULL DEFAULT 'manual_only' COMMENT '授权模式:manual_only/auto_draft/conditional_auto',
  `target_scope` varchar(32) NOT NULL DEFAULT 'none' COMMENT '作用对象:none/whitelist/friends/matched_only/custom',
  `risk_level` varchar(16) NOT NULL DEFAULT 'medium' COMMENT '风险级别:low/medium/high/critical',
  `max_amount_per_action` int NOT NULL DEFAULT 0 COMMENT '单次金额上限',
  `max_amount_per_day` int NOT NULL DEFAULT 0 COMMENT '单日金额上限',
  `max_actions_per_day` int NOT NULL DEFAULT 0 COMMENT '单日动作次数上限',
  `quiet_hours_json` text COMMENT '静默时段JSON',
  `policy_json` longtext COMMENT '额外策略JSON',
  `consent_version` varchar(32) NOT NULL DEFAULT '' COMMENT '确认的协议版本',
  `confirmed_at` datetime DEFAULT NULL COMMENT '用户确认时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_permission_user_capability` (`user_id`, `capability_code`),
  KEY `idx_agent_permission_enabled` (`enabled`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能恋爱助手能力授权表';

CREATE TABLE IF NOT EXISTS `agent_action_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `request_id` varchar(64) NOT NULL DEFAULT '' COMMENT '请求ID',
  `owner_user_id` int NOT NULL DEFAULT 0 COMMENT '主人用户ID',
  `target_user_id` int NOT NULL DEFAULT 0 COMMENT '目标用户ID',
  `capability_code` varchar(64) NOT NULL DEFAULT '' COMMENT '能力编码',
  `scene_code` varchar(64) NOT NULL DEFAULT '' COMMENT '场景编码',
  `risk_level` varchar(16) NOT NULL DEFAULT 'medium' COMMENT '风险级别',
  `status` varchar(32) NOT NULL DEFAULT 'draft' COMMENT '状态:draft/pending_approval/approved/running/succeeded/failed/rejected/cancelled/expired',
  `requires_approval` tinyint NOT NULL DEFAULT 1 COMMENT '是否需要审批:0否 1是',
  `approval_id` bigint NOT NULL DEFAULT 0 COMMENT '关联审批ID',
  `runtime_trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'runtime trace ID',
  `idempotency_key` varchar(64) NOT NULL DEFAULT '' COMMENT '幂等键',
  `operator_mode` varchar(32) NOT NULL DEFAULT 'assistant' COMMENT '执行模式:assistant/user/system',
  `scheduled_time` datetime DEFAULT NULL COMMENT '计划执行时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `policy_snapshot_json` longtext COMMENT '权限快照JSON',
  `plan_json` longtext COMMENT '动作计划JSON',
  `execution_json` longtext COMMENT '执行参数JSON',
  `result_json` longtext COMMENT '执行结果JSON',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '错误信息',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_action_task_request_id` (`request_id`),
  KEY `idx_agent_action_task_owner_status` (`owner_user_id`, `status`, `update_time`),
  KEY `idx_agent_action_task_target` (`target_user_id`, `capability_code`),
  KEY `idx_agent_action_task_trace` (`runtime_trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能恋爱助手动作任务表';

CREATE TABLE IF NOT EXISTS `agent_action_approval` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审批ID',
  `task_id` bigint NOT NULL DEFAULT 0 COMMENT '动作任务ID',
  `owner_user_id` int NOT NULL DEFAULT 0 COMMENT '主人用户ID',
  `target_user_id` int NOT NULL DEFAULT 0 COMMENT '目标用户ID',
  `capability_code` varchar(64) NOT NULL DEFAULT '' COMMENT '能力编码',
  `risk_level` varchar(16) NOT NULL DEFAULT 'high' COMMENT '风险级别',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/approved/rejected/expired/cancelled',
  `approval_payload_json` longtext COMMENT '审批展示数据JSON',
  `decision_note` varchar(255) NOT NULL DEFAULT '' COMMENT '审批备注',
  `decision_by_user_id` int NOT NULL DEFAULT 0 COMMENT '审批用户ID',
  `requested_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发起审批时间',
  `decided_at` datetime DEFAULT NULL COMMENT '审批完成时间',
  `expire_time` datetime DEFAULT NULL COMMENT '审批过期时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_action_approval_task_id` (`task_id`),
  KEY `idx_agent_action_approval_owner_status` (`owner_user_id`, `status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能恋爱助手动作审批表';

CREATE TABLE IF NOT EXISTS `agent_action_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路trace ID',
  `request_id` varchar(64) NOT NULL DEFAULT '' COMMENT '请求ID',
  `task_id` bigint NOT NULL DEFAULT 0 COMMENT '动作任务ID',
  `approval_id` bigint NOT NULL DEFAULT 0 COMMENT '审批ID',
  `owner_user_id` int NOT NULL DEFAULT 0 COMMENT '主人用户ID',
  `target_user_id` int NOT NULL DEFAULT 0 COMMENT '目标用户ID',
  `capability_code` varchar(64) NOT NULL DEFAULT '' COMMENT '能力编码',
  `event_type` varchar(64) NOT NULL DEFAULT '' COMMENT '事件类型',
  `event_status` varchar(32) NOT NULL DEFAULT 'success' COMMENT '事件状态',
  `source_type` varchar(32) NOT NULL DEFAULT 'java' COMMENT '来源:java/runtime/app/client',
  `risk_level` varchar(16) NOT NULL DEFAULT 'medium' COMMENT '风险级别',
  `message` varchar(255) NOT NULL DEFAULT '' COMMENT '日志消息',
  `payload_json` longtext COMMENT '事件载荷JSON',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_agent_action_log_trace` (`trace_id`),
  KEY `idx_agent_action_log_request` (`request_id`),
  KEY `idx_agent_action_log_task` (`task_id`, `create_time`),
  KEY `idx_agent_action_log_owner` (`owner_user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能恋爱助手审计日志表';
