CREATE TABLE IF NOT EXISTS `gift_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '礼物任务ID',
  `request_id` varchar(64) NOT NULL DEFAULT '' COMMENT '请求标识',
  `sender_uid` int NOT NULL DEFAULT 0 COMMENT '送礼用户ID',
  `target_uid` int NOT NULL DEFAULT 0 COMMENT '目标用户ID',
  `post_id` int NOT NULL DEFAULT 0 COMMENT '关联帖子ID',
  `session_id` varchar(64) NOT NULL DEFAULT '' COMMENT '关联会话ID',
  `reward_amount` int NOT NULL DEFAULT 0 COMMENT '打赏金额/爱情币',
  `gift_code` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物编码',
  `gift_name` varchar(40) NOT NULL DEFAULT '' COMMENT '礼物名称',
  `gift_icon` varchar(8) NOT NULL DEFAULT '' COMMENT '礼物图标',
  `gift_scene` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物场景',
  `gift_theme` varchar(24) NOT NULL DEFAULT '' COMMENT '礼物主题',
  `template_code` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物模板编码',
  `animation_preset` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物动效预设',
  `reveal_effect` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物拆盒特效预设',
  `sound_effect_key` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物音效键',
  `sound_effect_url` varchar(255) NOT NULL DEFAULT '' COMMENT '礼物音效地址',
  `relationship_stage` varchar(24) NOT NULL DEFAULT '' COMMENT '关系阶段',
  `provider` varchar(40) NOT NULL DEFAULT '' COMMENT '礼物策划提供方',
  `strategy_note` varchar(255) NOT NULL DEFAULT '' COMMENT '策略说明',
  `reason` varchar(255) NOT NULL DEFAULT '' COMMENT '推荐理由',
  `note` varchar(255) NOT NULL DEFAULT '' COMMENT '送礼文案',
  `visual_prompt` text COMMENT '礼物配图提示词',
  `motion_prompt` text COMMENT '礼物视频提示词',
  `reference_media` text COMMENT '参考图列表(JSON)',
  `generated_media` text COMMENT '生成图列表(JSON)',
  `gift_status` tinyint NOT NULL DEFAULT 0 COMMENT '礼物状态:0待接受 1已接受 2已拒绝 3已过期',
  `task_status` tinyint NOT NULL DEFAULT 0 COMMENT '任务状态:0待生成 1成功 2失败',
  `status_note` varchar(120) NOT NULL DEFAULT '' COMMENT '任务说明',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gift_task_request_id` (`request_id`),
  KEY `idx_gift_task_sender_uid` (`sender_uid`),
  KEY `idx_gift_task_target_uid` (`target_uid`),
  KEY `idx_gift_task_post_id` (`post_id`),
  KEY `idx_gift_task_status` (`task_status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI礼物任务表';

ALTER TABLE `gift_task`
  ADD COLUMN IF NOT EXISTS `template_code` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物模板编码' AFTER `gift_theme`,
  ADD COLUMN IF NOT EXISTS `animation_preset` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物动效预设' AFTER `template_code`,
  ADD COLUMN IF NOT EXISTS `reveal_effect` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物拆盒特效预设' AFTER `animation_preset`,
  ADD COLUMN IF NOT EXISTS `sound_effect_key` varchar(32) NOT NULL DEFAULT '' COMMENT '礼物音效键' AFTER `reveal_effect`,
  ADD COLUMN IF NOT EXISTS `sound_effect_url` varchar(255) NOT NULL DEFAULT '' COMMENT '礼物音效地址' AFTER `sound_effect_key`;
